"""
Verixa AI — Emergency Contact + Interaction Models
Two collections:
  emergency_contacts  — saved contacts per user
  (emergency SOS records saved to chat_history with module="emergency")
"""

from datetime import datetime, timezone
from typing import Optional
from pydantic import BaseModel, Field

class EmergencyContactDocument(BaseModel):
    """Represents a row in `emergency_contacts`."""
    user_id:      str
    name:         str
    phone:        str
    relationship: Optional[str] = None   # "family" | "friend" | "doctor"
    is_primary:   bool = False
    created_at:   datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    model_config = {"arbitrary_types_allowed": True}

class EmergencyAlertDocument(BaseModel):
    """Represents an SOS alert generated by a user.
    Stored in collection `emergency_alerts`.
    """
    user_id:        str
    latitude:       float
    longitude:      float
    maps_link:      str
    emergency_type: str  # e.g., "Medical", "Police", "Fire", "General"
    status:           str = "pending"   # pending | sent | failed
    whatsapp_status:  str = "pending"   # pending | success | mocked | failed
    delivery_status:  Optional[str] = "pending"
    meta_response_id: Optional[str] = None
    error_message:    Optional[str] = None
    created_at:       datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    # Optional alias for backward compatibility
    timestamp:        datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    model_config = {"arbitrary_types_allowed": True}
